apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: loadgenerator-svc
requires:
  - configs: [backend-svc]
  - git:
      repo: https://github.com/realArcherL/httpx
      # uses default `path` and `ref`